apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: expense-dev
  labels:
    app: nginx
    purpose: deployment
    tier: web
spec:
  replicas: 5
  stratey:
    type: rollingUpgrade
    rollingUpgrade:
      maxunavailable: 1
      maxsurge: 1

  selector:
    matchLabels:
      app: nginx
      tier: web
      project: test-project
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        project: test-project
        extra-key: extra-value
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: expense-dev
spec:
  selector:
    app: nginx
    tier: web
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 80 # container port
  type: ClusterIP
