apiVersion: v1 
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx 
      image: nginx
      env:
      - name: APP_NAME
        valuesFrom:
          configMapRef: 
            name: app-configmap
            key: APP_NAME
      - name: APP_ENV
        valuesFrom:
          configMapRef: 
            name: app-configmap
            key: APP_ENV
      ports:
        - containerPort: 80